kind: Application
apiVersion: nais.io/v1alpha1
metadata:
  name: pto-proxy
  namespace: pto
  labels:
    team: pto
spec:
  image: docker.pkg.github.com/navikt/pto-proxy/pto-proxy:{{version}}
  port: 8080
  ingresses:
    - https://pto-proxy.dev.nav.no
  prometheus:
    enabled: true
    path: /internal/prometheus
  liveness:
    path: /internal/isAlive
    initialDelay: 30
  readiness:
    path: /internal/isReady
    initialDelay: 30
  replicas:
    min: 1
    max: 2
    cpuThresholdPercentage: 75
  resources:
    limits:
      cpu: "1"
      memory: 1Gi
    requests:
      cpu: 500m
      memory: 512Mi

